---
- hosts: server
  tasks:
  - name: Update APT
    apt: update_cache=yes
    when: ansible_os_family == 'Debian'

  - name: Upgrade packages
    apt: upgrade=safe
    when: ansible_os_family == 'Debian'

  - name: Install default-jdk
    apt: 
        name: default-jdk
        state: latest

  - name: Install apt-transport-https
    apt:
            name: apt-transport-https
            state: latest
  
  - name: Add Elasticsearch GPG-KEY
    apt_key:
            url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
            state: present


  - name: Add Elasticsearch to source list
    apt_repository:
            repo: deb https://artifacts.elastic.co/packages/6.x/apt stable main 
            state: present
            filename: /etc/apt/sources.list.d/elastic-6.x.list

  - name: Install Elasticsearch
    apt:
            name: elasticsearch
            state: latest
            update_cache: yes

  - name: Install Kibana
    apt:
            name: kibana
            state: latest

            
  - name: Add Grafana GPG-KEY
    apt_key:
            url: https://packagecloud.io/gpg.key
            state: present

  - name: Add Elasticsearch to source list
    apt_repository:
            repo: deb https://packagecloud.io/grafana/stable/debian/ jessie main 
            state: present
            
  - name: Install Grafana
    apt:
            name: grafana
            state: latest
            update_cache: yes

  - name: Reconfigure Elasticsearch to listen on 0.0.0.0:9200
    lineinfile:
            path: /etc/elasticsearch/elasticsearch.yml
            line: 'network.host: 0.0.0.0'


  - name: Reconfigure Kibana to listen on 0.0.0.0:5601
    lineinfile:
            path: /etc/kibana/kibana.yml
            line: 'server.host: "0.0.0.0"'

  - name: Restarting Elasticsearch Service
    service:
          name: elasticsearch
          state: restarted

  - name: Restarting Kibana Service
    service:
          name: kibana
          state: restarted

  - name: Restarting Grafana Service
    service:
          name: grafana-service
          state: restarted
